[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_native_swaps = "GfCxk9H9EoHP7cvophozquwRTkkm3ierP6sVUWKBBwCe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.ts"
